name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install mesa-common-dev libx11-dev libxfixes-dev libxcomposite-dev libc6-dev gcc g++ make
    
    - name: Build
      run: make
